// Generated by Wrangler on Sun Jun 09 2024 00:06:45 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_CLIENT_CALLBACK_URL: string;
	SESSION_SECRET: string;
	RESEND_ID: string;
	RESEND_API_KEY: string;
	R2: R2Bucket;
	DB: D1Database;
}
